### ISSUE TITLE
Possible optimization: Glowcase's text optimizations for signs

### ISSUE THREAD

**Issue by TropheusJ** [ModFest/fireblanket#1]
Signs are still notable on profiles. Maybe Glowcase's text optimizations could be applied to signs? I am not sure of how exactly it works so I don't know how feasible this is.

**Comment by exaskye** [comment]
Most of the signs on the server are for PictureSign, so ideally we would detect "hidden" signs and just prevent the vanilla part being rendered entirely. This can be done quickly by just checking if they're at light level 0.
