### ISSUE TITLE
Block/entity tag adventure interaction blacklist

### ISSUE THREAD

**Issue by sisby-folk** [ModFest/fireblanket#19]
It'd be great to have a block tag that blacklisted adventure mode players from interaction - could cover the classic problem cases like trapdoors, dispensers, droppers, barrels, chests, shulker boxes, trapped chests. 

Easy enough to just datapack customize that if it needs to be looser

An entity tag would be nice too, for item frames.

**Comment by HamaIndustries** [comment]
fixed by 020f8ac (leaving open so you can verify)
