### ISSUE TITLE
Possible optimization: hiding block entities

### ISSUE THREAD

**Issue by TropheusJ** [ModFest/fireblanket#2]
I'm sure there's plenty of block entities on the server that are needed only for behavior, not visuals. Create's train stations are a good example, and take up a surprising amount of render time. 
I think you should be able to flag a block entity somehow to make it skip rendering, ideally entirely avoiding the block entity rendering list.

**Comment by exaskye** [comment]
Sodium seems to already do this, but Fireblanket has a mixin to intentionally break this behavior so that it can render a mask when needed. BE masking should probably be turned off in pack builds, and only enabled when someone is debugging.

**Comment by jaskarth** [comment]
I agree, while adding BEs with null BERs isn't necessarily *incorrect*, it introduces significant overhead in processing and managing the BE list. While intended to be disabled before the con, I think it is definitely reasonable to disable it now for build participants as well.

**Comment by exaskye** [comment]
I think this can be considered fixed now that BE masking is off by default, as that was the real cause.
